### ISSUE TITLE
Flag --skip-folders does not always work

### ISSUE THREAD

**Issue by lk16** [lk16/detect-missing-init#3]
Below summary is for a potential bug, as posted by @paveldedik in #2:

But as I was testing it, even the `--skip-folders` option doesn't seem to be working as expected, I have the following:

    -   repo: https://github.com/lk16/detect-missing-init
        rev: v0.1.4
        hooks:
        -   id: detect-missing-init
            args: ['--skip-folders=client']
The client folder is in the root (where `.pre-commit-config.yaml` is) and it is NOT being skipped.

**Comment by lk16** [comment]
I tried to reproduce this in a minimal setup and could not trigger the bug.

I added one file `client/bar.py` and the pre-commit config to a new repo. 
No other files are present in this test folder (except for `.git`).

See below shell session:
```
foo (master) $ pwd
/tmp/foo
foo (master) $ git ls-files
.pre-commit-config.yaml
client/bar.py
foo (master) $ pre-commit run -a detect-missing-init
Detect missing __init__.py...............................................Passed
```

Next thing I did is to commit the above 2 files and try to create a file in a subfolder of `client`:
```
foo (master) $ mkdir client/baz
foo (master) $ touch client/baz/quux.py
foo (master) $ git add .
foo (master) $ pre-commit run -a detect-missing-init
Detect missing __init__.py...............................................Failed
- hook id: detect-missing-init
- exit code: 1

/tmp/foo/client/baz/__init__.py
Found 1 missing __init__.py file(s).
```

This works as expected as well.

@paveldedik Could you please elaborate about your folder structure in your repo so I can reproduce it and fix the problem?

**Comment by paveldedik** [comment]
Thank you, I will try to provide minimal reproducible example ASAP

**Comment by lk16** [comment]
The `--skip-folders` flag does not exist anymore since v0.1.5. Therefore I'm closing this issue.
